// icon-set-variable.test.ts — a vector's paint is a per-instance knob.
//
// Framer's own icons declare their colour as a variable and expose it as a
// Color control (`@framerVector {"color":{"type":"variable",…}}`), which is
// how one arrow serves a black button and an orange one. A set that cannot do
// the same has to bake one file per colour.
//
// The binding goes in the shape's STYLE OBJECT, not the `fill` attribute:
// that is the only form the parser tags `var:` and the panel reads back.

import { describe, it, expect, vi } from 'vitest';

vi.mock('@/shared/debug-trace', () => ({ trace: { action: vi.fn(), fn: vi.fn(), error: vi.fn() } }));

import { createVariableInCode } from './variable-ops';

// The shape buildIconSetFile emits: module-scope helpers first, then the
// component as a `React.forwardRef(function …)` — a FunctionExpression.
const ICON_SET = `'use client';
import React from 'react';
import { motion } from 'framer-motion';
import { withResponsiveProps } from '@revyme/runtime';

/** @name "Arrows" */
/** @iconSet */

const iconConfig = [
  { name: 'icon-1', label: 'Arrow Right', x: 0, y: 0, width: 240, height: 240, isPrimary: true },
];

function svgIdsIn(node, out) { return out; }
function scopeUrlRefs(value, uid, ids) { return value; }
function scopeSvgIds(node, uid, ids) { return node; }

const Arrows = React.forwardRef(function Arrows({ name, style, children, ...rest }, ref) {
  const master = (
    <div data-id="root" data-name="Icons" style={{ position: 'relative', width: '100%', height: '100%' }}>
      <div data-id="icon-1" data-name="Arrow Right" style={{ backgroundColor: '#ffffff' }}>
        <svg data-id="icon-1-svg" viewBox="0 0 24 24" style={{ position: 'absolute' }}>
          <path data-id="icon-1-p0" d="M 0 7 L 18 7" style={{ fill: '#cccccc' }} />
        </svg>
      </div>
    </div>
  );
  if (!name) return scoped(master);
  return null;
});

export default withResponsiveProps(Arrows);
`;

describe('creating a variable on a vector inside an icon set', () => {
  const out = () => createVariableInCode(ICON_SET, 'icon-1-p0', 'fill', 'iconFill', '#cccccc');

  // The component is a FunctionExpression wrapped in React.forwardRef. The
  // prop walker only visited FunctionDeclaration / ArrowFunctionExpression, so
  // it never reached it and the whole operation silently no-opped.
  it('adds the prop to the forwardRef signature', () => {
    expect(out()).toContain('function Arrows({ name, style, children, iconFill = "#cccccc", ...rest }, ref)');
  });

  // …before `...rest`, or the prop is swallowed by the spread and lands on the
  // instance's motion.div as an unknown DOM attribute.
  it('keeps the rest element last', () => {
    const sig = out().split('\n').find((l) => l.includes('forwardRef(function'))!;
    expect(sig.indexOf('iconFill')).toBeLessThan(sig.indexOf('...rest'));
  });

  it('binds the shape through its style object', () => {
    expect(out()).toContain('style={{ fill: iconFill }}');
  });

  // The file's module-scope helpers take a plain identifier as their first
  // parameter; none of them may be turned into the component by accident.
  it('leaves the svg-id helpers alone', () => {
    const o = out();
    expect(o).toContain('function svgIdsIn(node, out)');
    expect(o).toContain('function scopeUrlRefs(value, uid, ids)');
    expect(o).toContain('function scopeSvgIds(node, uid, ids)');
  });

  // Everything from the instance-branch marker to EOF is regenerated by
  // upgradeVectorSetInstanceBranch, so nothing may be written after it.
  it('writes nothing below the instance-branch marker', () => {
    const o = out();
    expect(o.slice(o.indexOf('if (!name) return'))).not.toContain('iconFill');
  });
});
